site_name: RoenSpace
site_url: https://jeroenkroesen.github.io/Roenblog/
theme:
  name: material
  palette:
    scheme: slate
  logo: _resources/roenicon_new.png
  features:
    - navigation.path
    - content.code.copy
  favicon: _resources/favicon.png
plugins:
  - search
  - blog
  - meta
  - tags:
      listings_toc: false
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  generator: false
copyright: Copyright &copy; 2025 Jeroen Kroesen
